export const PROJECTS = [
    {
        num: '01', 
        category: 'Frontend Development', 
        title: 'Kartera', 
        description:"Application is a Cost-effective Alternative Approach to Payment Processing that accepts low-cost payments directly from your customer's bank account",
        image: '/assets/work/kartera.png',
        live: 'https://kartera.com',
        github: '',
        stack: [
            { name: 'React' },
            { name: 'Redux' },
            { name: 'Typescript' },
            { name: 'Mui' },
            { name: 'Storybook' },
        ], 
    },
    {
        num: '02',
        category: 'FullStack Development',
        title: 'SAVAM web',
        description:'A Business Intelligence (BI) application that seamlessly consolidates and analyzes data from more than 10 diverse sources. This comprehensive tool not only generates insightful reports but also facilitates real-time notifications.',
        image: '/assets/work/savamweb.png',
        live: 'https://campolimpo.savamweb.com.br/',
        github: 'https://github.com/fhalbiero/savamweb-frontend',
        stack: [
            { name: 'ReactJS' },
            { name: 'Styled Components' },
            { name: 'NodeJS' },
            { name: 'JWT' },
            { name: 'MySQL' },
            { name: 'GraphQL' },
            { name: 'Context API' },
            { name: 'Puppeteer' },
        ],
    },
    {
        num: '03',
        category: 'Frontend Development',
        title: 'Rick and Morty',
        description:'A React application designed for educational purposes, demonstrating the use of GraphQL with pagination in a simple single-page setup. This project serves as a practical learning resource for integrating GraphQL and efficiently managing paginated data within a minimalistic web application.',
        image: '/assets/work/rickandmorty.png',
        live: 'https://rick-and-morty-app-graphql-puce.vercel.app/',
        github: 'https://github.com/fhalbiero/rick-and-morty-app-graphql',
        stack: [
            { name: 'ReactJS' },
            { name: 'GraphQL' },
            { name: 'Apollo' },
            { name: 'Styled Components' },
            { name: 'Context API' },
            { name: 'Local Storage' },
        ],
    },
    {
        num: '04',
        category: 'Frontend Development',
        title: 'Github Explorer',
        description:'An educational React application, this project showcases proficiency in React Router v6, TypeScript, and structured code integration with the GitHub API. It demonstrates efficient data management within a minimalist web application, leveraging Tailwind CSS for a sleek and modern design.',
        image: '/assets/work/gitexplorer.png',
        live: 'https://fh-git-explorer.vercel.app/',
        github: 'https://github.com/fhalbiero/git_explorer',
        stack: [
            { name: 'React' },
            { name: 'React Router v6' },
            { name: 'Tailwind CSS' },
            { name: 'TypeScript' },
            { name: 'GitHub API' },
            { name: 'Vite' },
        ],
    },
    {
        num: '05',
        category: 'Mobile Development',
        title: 'Trvlar',
        description:'A React Native application designed to facilitate travel planning and organization. This project showcases the integration of React Native, Styled Components, and TypeScript to create a user-friendly mobile application that efficiently manages travel itineraries and expenses.',
        image: '/assets/work/trvlar.png',
        live: '',
        github: 'https://github.com/trvlar/Trvlar2',
        stack: [
            { name: 'React Native' },
            { name: 'Styled Component' },
            { name: 'Typescript' },
            { name: 'NodeJS' },
            { name: 'Mongo DB' },
        ],
    },
    {
        num: '06',
        category: 'Frontend Development',
        title: 'Pomodoro countdown',
        description:'An educational React application that implements a Pomodoro countdown timer. This project serves as a practical learning tool, showcasing the integration of React to create a focused and effective time management tool based on the Pomodoro technique.',
        image: '/assets/work/pomodoro.png',
        live: 'https://fhalbiero-pomodoro.vercel.app/',
        github: 'https://github.com/fhalbiero/pomodoro/',
        stack: [
            { name: 'Typescript' },
            { name: 'ReactJS' },
            { name: 'Styled Components' },
            { name: 'Vite' },
            { name: 'Context API' },
            { name: 'Theme Provider' },
        ],
    },
    {
        num: '07',
        category: 'FullStack Development',
        title: 'Go Barber',
        description:'Application developed for managing appointments in barber shops.',
        image: '',
        live: '',
        github: 'https://github.com/fhalbiero/goBarber-web',
        stack: [
            { name: 'ReactJS' },
            { name: 'NodeJs' },
            { name: 'Postgres' },
            { name: 'MongoDB' },
            { name: 'Redis' },
            { name: 'TypeORM' },
            { name: 'JWT' },
        ],
    },
    {
        num: '08',
        category: 'FullStack Development',
        title: 'CRWN Clothing',
        description:'Created to learn more about e-commerces, payment integration and consolidate Redux and Redux-Sagas concepts.',
        image: '/assets/work/clothings.png',
        live: 'http://clothings.fabioalbiero.com/',
        github: 'https://github.com/fhalbiero/crwn-clothing',
        stack: [
            { name: 'React' },
            { name: 'Redux' },
            { name: 'SAGA' },
            { name: 'Firebase' },
            { name: 'OAuth' },
            { name: 'Styled-Components' },
        ],
    },
    {
        num: '09',
        category: 'API Learning',
        title: 'Pokédex',
        description:'Developed for fun and to learn more about APIs and Pokemons.',
        image: '/assets/work/pokemon.png',
        live: 'https://fhalbiero.github.io/pokedex/',
        github: 'https://github.com/fhalbiero/pokedex',
        stack: [
            { name: 'ReactJS' },
            { name: 'API' },
            { name: 'Axios' },
            { name: 'Context API' },
            { name: 'Styled Components' },
        ],
    },
    {
        num: '10',
        category: 'Frontend Development',
        title: 'Coronavirus-Tracker',
        description:'Application developed to track the spread of the coronavirus worldwide and show the number of cases, deaths, and recoveries in real-time.',
        image: '/assets/work/covid.png',
        live: 'https://fhalbiero.github.io/coronavirus-tracker/',
        github: 'https://github.com/fhalbiero/coronavirus-tracker',
        stack: [
            { name: 'ReactJS' },
            { name: 'API Integration' },
            { name: 'SVG' },
            { name: 'CSS' },
        ],
    },
    {
        num: '11',
        category: 'Frontend Development',
        title: 'FH Money',
        description:'Created for learning purpose to consolidate and improve React, Typescript, ContextAPI and Styled Components concepts.',
        image: '',
        live: 'http://money.fabioalbiero.com/',
        github: 'https://github.com/fhalbiero/fh-money',
        stack: [
            { name: 'React' },
            { name: 'Typescript' },
            { name: 'Axios' },
            { name: 'MirageJS' },
            { name: 'Styled-Components' },
        ],
    },
    {
        num: '12',
        category: 'Municipal Service Management',
        title: 'SIGISS WEB',
        description:'Municipal service tax management system and electronic invoice',
        image: '/assets/work/sigissweb.png',
        live: 'https://sumare.sigissweb.com/',
        github: '',
        stack: [
            { name: 'Java' },
            { name: 'JSP' },
            { name: 'Servlet' },
            { name: 'JDBC' },
            { name: 'SQL Server' },
            { name: 'iReport' },
            { name: 'Javascript' },
            { name: 'jQuery' },
            { name: 'Ajax' },
        ],
    },
    {
        num: '13',
        category: 'Portfolio',
        title: 'Portfolio',
        description:'This Portfolio',
        image: '/assets/work/portfolio.png',
        live: 'https://fabioalbiero.com',
        github: 'https://github.com/fhalbiero/myportifolio/',
        stack: [
            { name: 'React' },
            { name: 'Styled components' },
        ],
    },
    {
        num: '14',
        category: 'Learning',
        title: 'Money Converter',
        description:'App created to learn how integrate with APIs',
        image: '',
        live: 'https://fhalbiero.github.io/money-converter/',
        github: 'https://github.com/fhalbiero/money-converter/',
        stack: [
            { name: 'React' },
            { name: 'API' },
            { name: 'GH Pages' },
        ],
    },
    {
        num: '15',
        category: 'Learning',
        title: 'Monsters Rolodex',
        description:'App created to learn how integrate with APIs',
        image: '',
        live: 'https://fhalbiero.github.io/card-monsters/',
        github: 'https://github.com/fhalbiero/card-monsters/',
        stack: [
            { name: 'React' },
            { name: 'API' },
            { name: 'Redux' },
            { name: 'GH Pages' },
        ],
    },
    {
        num: '16',
        category: 'Learning',
        title: 'If I were...',
        description:'App created to learn how integrate with APIs',
        image: '',
        live: 'https://fhalbiero.github.io/if-i-were/',
        github: 'https://fabioalbiero.com',
        stack: [
            { name: 'React' },
            { name: 'GH Pages' },
        ],
    },
    {
        num: '17',
        category: 'Web Development',
        title: 'GLC Web Site',
        description:'Web site for a development company',
        image: '/assets/work/glcconsultoria.png',
        live: 'http://glcconsultoria.com.br/',
        github: '',
        stack: [
            { name: 'HTML5' },
            { name: 'CSS3' },
            { name: 'Grid' },
            { name: 'Responsive' },
        ],
    },
    {
        num: '18',
        category: 'Web Development',
        title: 'Web Site Natours',
        description:'Created to learn new CSS3 resources and SASS',
        image: '',
        live: 'https://fabioalbiero.com',
        github: 'https://fabioalbiero.com',
        stack: [
            { name: 'HTML5' },
            { name: 'CSS3' },
            { name: 'SASS' },
        ],
    }
];
    