export const PROJECTS = [
    {
        num: '01', 
        category: 'Frontend Development', 
        title: 'Kartera', 
        description:"Application is a Cost-effective Alternative Approach to Payment Processing that accepts low-cost payments directly from your customer's bank account",
        image: '/assets/work/kartera.png',
        live: 'https://kartera.com',
        github: '',
        stack: [
            { name: 'React' },
            { name: 'Redux' },
            { name: 'Typescript' },
            { name: 'Mui' },
            { name: 'Storybook' },
        ], 
    },
    {
        num: '02',
        category: 'Business Intelligence',
        title: 'SAVAM web',
        description:'A Business Intelligence (BI) application that seamlessly consolidates and analyzes data from more than 10 diverse sources. This comprehensive tool not only generates insightful reports but also facilitates real-time notifications.',
        image: '/assets/work/savamweb.png',
        live: 'https://campolimpo.savamweb.com.br/',
        github: '',
        stack: [
            { name: 'ReactJS' },
            { name: 'Styled Components' },
            { name: 'NodeJS' },
            { name: 'JWT' },
            { name: 'MySQL' },
            { name: 'GraphQL' },
            { name: 'Context API' },
            { name: 'Puppeteer' },
        ],
    },
    {
        num: '03',
        category: 'Education',
        title: 'Rick and Morty',
        description:'A React application designed for educational purposes, demonstrating the use of GraphQL with pagination in a simple single-page setup. This project serves as a practical learning resource for integrating GraphQL and efficiently managing paginated data within a minimalistic web application.',
        image: '/assets/work/rickandmorty.png',
        live: 'https://rick-and-morty-app-graphql-puce.vercel.app/',
        github: 'https://github.com/fhalbiero/rick-and-morty-app-graphql',
        stack: [
            { name: 'ReactJS' },
            { name: 'GraphQL' },
            { name: 'Apollo' },
            { name: 'Styled Components' },
            { name: 'Context API' },
            { name: 'Local Storage' },
        ],
    },
    {
        num: '04',
        category: 'Learning',
        title: 'Github Explorer',
        description:'An educational React application, this project showcases proficiency in React Router v6, TypeScript, and structured code integration with the GitHub API. It demonstrates efficient data management within a minimalist web application, leveraging Tailwind CSS for a sleek and modern design.',
        image: '/assets/work/gitexplorer.png',
        live: 'https://fh-git-explorer.vercel.app/',
        github: 'https://github.com/fhalbiero/git_explorer',
        stack: [
            { name: 'React' },
            { name: 'React Router v6' },
            { name: 'Tailwind CSS' },
            { name: 'TypeScript' },
            { name: 'GitHub API' },
            { name: 'Vite' },
        ],
    },
    {
        num: '05',
        category: 'Web Development',
        title: 'Trvlar',
        description:'A webpage created using ReactJS and Tailwind CSS. This project was developed to showcase the Trvlar application, a volunteer project that aims to provide a platform for travelers to share their experiences and connect with other travelers. The webpage features a responsive design and a clean layout, highlighting the key features of the Trvlar application.',
        image: '/assets/work/trvlar.png',
        live: '',
        github: '',
        stack: [
            { name: 'ReactJS' },
            { name: 'Tailwind' },
            { name: 'Parallax' },
            { name: 'Typescript' },
        ],
    },
    {
        num: '06',
        category: 'Time Management',
        title: 'Pomodoro countdown',
        description:'An educational React application that implements a Pomodoro countdown timer. This project serves as a practical learning tool, showcasing the integration of React to create a focused and effective time management tool based on the Pomodoro technique.',
        image: '/assets/work/pomodoro.png',
        live: 'https://fhalbiero-pomodoro.vercel.app/',
        github: 'https://github.com/fhalbiero/pomodoro/',
        stack: [
            { name: 'Typescript' },
            { name: 'ReactJS' },
            { name: 'Styled Components' },
            { name: 'Vite' },
            { name: 'Context API' },
            { name: 'Theme Provider' },
        ],
    },
    {
        num: '07',
        category: 'Appointments Management',
        title: 'Go Barber',
        description:'Application developed for managing appointments in barber shops.',
        image: '',
        live: '',
        github: 'https://github.com/fhalbiero/goBarber-web',
        stack: [
            { name: 'NodeJs' },
            { name: 'ReactJS' },
            { name: 'React Native' },
            { name: 'Postgres' },
            { name: 'MongoDB' },
            { name: 'Redis' },
            { name: 'TypeORM' },
            { name: 'JWT' },
        ],
    },
    {
        num: '08',
        category: 'E-commerce Learning',
        title: 'CRWN Clothing',
        description:'Created to learn more about e-commerces, payment integration and consolidate Redux and Redux-Sagas concepts.',
        image: '/assets/work/clothings.png',
        live: 'http://clothings.fabioalbiero.com/',
        github: 'https://github.com/fhalbiero/crwn-clothing',
        stack: [
            { name: 'React' },
            { name: 'Redux' },
            { name: 'SAGA' },
            { name: 'Firebase' },
            { name: 'OAuth' },
            { name: 'Styled-Components' },
        ],
    },
    {
        num: '09',
        category: 'API Learning',
        title: 'Pokédex',
        description:'Developed for fun and to learn more about APIs and Pokemons.',
        image: '/assets/work/pokemon.png',
        live: 'https://fhalbiero.github.io/pokedex/',
        github: 'https://github.com/fhalbiero/pokedex',
        stack: [
            { name: 'ReactJS' },
            { name: 'API' },
            { name: 'Axios' },
            { name: 'Context API' },
            { name: 'Styled Components' },
        ],
    },
    {
        num: '10',
        category: 'Tracker Application',
        title: 'Coronavirus-Tracker',
        description:'Application created to show worldwide information about coronavirus.',
        image: '/assets/work/covid.png',
        live: 'https://fhalbiero.github.io/coronavirus-tracker/',
        github: 'https://github.com/fhalbiero/coronavirus-tracker',
        stack: [
            { name: 'React' },
            { name: 'API Integration' },
            { name: 'SVG' },
            { name: 'CSS' },
        ],
    },
    {
        num: '11',
        category: 'Finance Management',
        title: 'FH Money',
        description:'Created for learning purpose to consolidate and improve React, Typescript, ContextAPI and Styled Components concepts.',
        image: '',
        live: 'http://money.fabioalbiero.com/',
        github: 'https://github.com/fhalbiero/fh-money',
        stack: [
            { name: 'React' },
            { name: 'Typescript' },
            { name: 'Axios' },
            { name: 'MirageJS' },
            { name: 'Styled-Components' },
        ],
    }
];
    